# Generated by Django 5.1.5 on 2025-01-24 06:29

import apps.common.model_fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_amenities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('area', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=512)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19, unique=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19, unique=True)),
                ('janitor', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('phonenumber', apps.common.model_fields.AppPhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'unisex')], max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_properties',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('single occupancy', 'Single Occupancy'), ('double occupancy', 'Double Occupancy'), ('triple occupancy', 'Triple Occupancy'), ('quadruple occupancy', 'Quadruple Occupancy'), ('quintuple occupancy', 'Quintuple Occupancy'), ('sixtuple occupancy', 'Sixtuple Occupancy')], max_length=512, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_room_types',
            },
        ),
        migrations.CreateModel(
            name='PropertyRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_property_rooms',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_property_amenities',
                'constraints': [models.UniqueConstraint(fields=('property', 'amenity'), name='unique_property_amenities')],
            },
        ),
        migrations.CreateModel(
            name='PropertyRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField()),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_Available', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_property_room_types',
                'constraints': [models.UniqueConstraint(fields=('property', 'room_type'), name='unique_property_room_type')],
            },
        ),
    ]
