# Generated by Django 5.1.5 on 2025-02-04 07:07

import apps.common.model_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('properties', '0001_initial'), ('properties', '0002_rename_capacity_propertyroomtype_capacity_and_more'), ('properties', '0003_alter_roomtype_capacity'), ('properties', '0004_remove_propertyroomtype_per_room_capacity_and_more'), ('properties', '0005_rename_is_available_propertyroomtype_is_bed_available_and_more'), ('properties', '0006_rename_total_capacity_propertyroomtype_total_capacity_and_more'), ('properties', '0007_bed'), ('properties', '0008_alter_bed_bed_number'), ('properties', '0009_remove_propertyrooms_property_and_more'), ('properties', '0010_timeslot'), ('properties', '0011_propertyschedulevisit'), ('properties', '0012_propertyschedulevisit_is_cancelled'), ('properties', '0013_booking_payment_alter_bed_options_and_more'), ('properties', '0014_payment_razorpay_payment_link_order_id'), ('properties', '0015_bed_room_type_bed_user_alter_booking_status'), ('properties', '0016_auto_20250203_1451'), ('properties', '0017_remove_bed_bed_number_remove_bed_is_available_and_more'), ('properties', '0018_bed_bed_number_bed_is_available_bed_room_type_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_amenities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('area', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=512)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19, unique=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19, unique=True)),
                ('janitor', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('phonenumber', apps.common.model_fields.AppPhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_properties',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('single occupancy', 'Single Occupancy'), ('double occupancy', 'Double Occupancy'), ('triple occupancy', 'Triple Occupancy'), ('quadruple occupancy', 'Quadruple Occupancy'), ('quintuple occupancy', 'Quintuple Occupancy'), ('sixtuple occupancy', 'Sixtuple Occupancy')], max_length=512, unique=True)),
                ('capacity', models.PositiveIntegerField(default=None, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_room_types',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_property_amenities',
                'constraints': [models.UniqueConstraint(fields=('property', 'amenity'), name='unique_property_amenities')],
            },
        ),
        migrations.CreateModel(
            name='PropertyRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_capacity', models.PositiveIntegerField(default=None, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_bed_available', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype')),
                ('number_of_rooms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_property_room_types',
                'constraints': [models.UniqueConstraint(fields=('property', 'room_type'), name='unique_property_room_type')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_timeslots',
            },
        ),
        migrations.CreateModel(
            name='PropertyScheduleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_schedule_visits',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('property_room_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.propertyroomtype')),
                ('bed_number', models.CharField(default=None, max_length=512, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('room_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property_room_type', 'bed_number'), name='unique_bed_in_room')],
                'ordering': ['-created_at'],
                'default_related_name': 'related_beds',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('allotted', 'Bed Allotted'), ('moved_in', 'Moved In')], default='pending', max_length=512)),
                ('bed', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.bed')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_bookings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(max_length=512, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('razorpay_signature', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='properties.booking')),
                ('razorpay_payment_link_order_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_payments',
            },
        ),
    ]
