# Generated by Django 5.1.5 on 2025-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyroomtype',
            old_name='capacity',
            new_name='Capacity',
        ),
        migrations.RenameField(
            model_name='propertyroomtype',
            old_name='number_of_rooms',
            new_name='Total_capacity',
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='per_Room_capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
