# Generated by Django 5.1.5 on 2025-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_capacity_propertyroomtype_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
