# Generated by Django 5.1.5 on 2025-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_roomtype_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyroomtype',
            name='per_Room_capacity',
        ),
        migrations.AlterField(
            model_name='propertyroomtype',
            name='Capacity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertyroomtype',
            name='Total_capacity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
