# Generated by Django 5.1.5 on 2025-01-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_propertyroomtype_per_room_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyroomtype',
            old_name='is_Available',
            new_name='is_bed_available',
        ),
        migrations.RemoveField(
            model_name='propertyroomtype',
            name='Capacity',
        ),
    ]
