# Generated by Django 5.1.5 on 2025-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_is_available_propertyroomtype_is_bed_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyroomtype',
            old_name='Total_capacity',
            new_name='total_capacity',
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
