# Generated by Django 5.1.5 on 2025-01-26 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_total_capacity_propertyroomtype_total_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('bed_number', models.PositiveIntegerField()),
                ('property_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.propertyroomtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property_room_type', 'bed_number'), name='unique_bed_in_room')],
            },
        ),
    ]
