# Generated by Django 5.1.5 on 2025-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(max_length=512),
        ),
    ]
