# Generated by Django 5.1.5 on 2025-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_bed_bed_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrooms',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyrooms',
            name='room_type',
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='bed',
            name='unique_bed_in_room',
        ),
        migrations.AlterField(
            model_name='property',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=512),
        ),
        migrations.DeleteModel(
            name='PropertyRooms',
        ),
    ]
