# Generated by Django 5.1.5 on 2025-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyschedulevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyschedulevisit',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
