# Generated by Django 5.1.5 on 2025-01-31 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_propertyschedulevisit_is_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_bookings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(max_length=512, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('razorpay_signature', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_payments',
            },
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'default_related_name': 'related_beds', 'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('property_room_type', 'bed_number'), name='unique_bed_in_room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.bed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='properties.booking'),
        ),
    ]
