# Generated by Django 5.1.5 on 2025-02-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_booking_payment_alter_bed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_link_order_id',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
