# Generated by Django 5.1.5 on 2025-02-03 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_payment_razorpay_payment_link_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='room_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('allotted', 'Bed Allotted'), ('moved_in', 'Moved In')], default='pending', max_length=512),
        ),
    ]
