# Generated by Django 5.1.5 on 2025-02-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_bed_room_type_bed_user_alter_booking_status'),
    ]

    operations = [
    ]
