# Generated by Django 5.1.5 on 2025-02-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20250203_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_number',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='user',
        ),
    ]
