# Generated by Django 5.1.5 on 2025-02-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_squashed_0018_bed_bed_number_bed_is_available_bed_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyroomtype',
            name='number_of_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
