# Generated by Django 5.1.5 on 2025-02-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('customer', 'Customer'), ('admin', 'Admin')], default='guest', max_length=512),
        ),
    ]
