version: '3'

volumes:
  production_postgres_data: { }

services:
  postgres:
    build:
      context: ../../
      dockerfile: ./docker/deployment/dockerfiles/Dockerfile-postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - ../../backups:/backups:z
    env_file:
      - ../../.env
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: iiht_b2b_backend
